### ISSUE TITLE
Http error when uploading photos

### ISSUE THREAD

**Issue by alexdaums** [bensonarts/GalleryCMS#1]
Hello!
I have the same problem.

"Reported by craigthe...@gmail.com, Apr 18, 2012
Hi all, 
have just installed gallery and created my first album.
When I try to upload a photo I get 'http error'

could this be a problem with my host or am i missing something?
Thanks "

**Comment by bensonarts** [comment]
What file type are you trying to upload? Currently PNGs cause an issue.

On Thu, Apr 26, 2012 at 10:35 AM, alexdaums <
reply@reply.github.com

> wrote:
> 
> Hello!
> I have the same problem.
> 
> "Reported by craigthe...@gmail.com, Apr 18, 2012
> Hi all,
> have just installed gallery and created my first album.
> When I try to upload a photo I get 'http error'
> 
> could this be a problem with my host or am i missing something?
> Thanks "
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bensonarts/GalleryCMS/issues/1

## 

_Aaron Benson_

**Comment by alexdaums** [comment]
No just jpeg file. 
I saw the bug for png file .

**Comment by alexdaums** [comment]
Hi,

My host is debian testing + apache2 + php5.4

Thanks

**Comment by bensonarts** [comment]
Fixed: https://github.com/bensonarts/GalleryCMS/commit/9cf0fb7cfa40a7614bfccf9b1b8094451a673d3b

I forgot that the uploads directory was in gitignore - so the directory never got created during the installation process. I merged this to the v2.0 tag.

**Comment by zanemeister** [comment]
I am also having the same issue. I tried the fix above but it did not correct the issue. Is there something else to try?

**Comment by bensonarts** [comment]
Do you have an uploads folder? I messed up my installer with the last
download package.
On May 2, 2012 8:28 PM, "zanemeister" <
reply@reply.github.com>
wrote:

**Comment by zanemeister** [comment]
A simple solution. Thanks a bunch. I think your gallery cms is going to be
very useful.
Zane

On Wed, May 2, 2012 at 9:02 PM, Aaron Benson <
reply@reply.github.com

**Comment by alexdaums** [comment]
Fixed

**Comment by bensonarts** [comment]
Can you verify that it was fixed because of my latest update, or was did
you fix it by doing something else?

On Thu, May 3, 2012 at 1:35 PM, alexdaums <
reply@reply.github.com

> wrote:
> 
> Fixed
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bensonarts/GalleryCMS/issues/1#issuecomment-5494787

## 

_Aaron Benson_

**Comment by alexdaums** [comment]
Hello, sorry for my english...

I created the missing folder based on your patch.
But it works correctly for a new installation.

**Comment by Deathmanlp** [comment]
I still have this problem. Im running version 2.0 on XAMPP. I have a uploads folder created during the installation. Filetype: JPG    file_uploads  On PHP 5.3.0

**Comment by Tombarr** [comment]
I'm also confused, I just downloaded the latest build today and I do in fact have an uploads directory 755 on PHP 5.3.0 CentOS, Apache, MySQL, etc. but still I get an HTTP error no matter what images (JPG, PNG, or GIF) or file size. The loader reaches 100% then says HTTP Error.

**Comment by adammockor** [comment]
Hello!

I have same issue on windows with XAMPP... uploads directory is created seems to be correctly...

**Comment by adammockor** [comment]
This http://stackoverflow.com/questions/10198439/getting-uploadify-working-with-codeigniter-302-http-error resolved my problem with uploading.

**Comment by bensonarts** [comment]
Merged xPAdAMx's pull request.

**Comment by trouille2** [comment]
I needed to change the folder 'uploads' chmod to 777.

**Comment by rubensitocom** [comment]
After few hours bugfixing I've the solution!

got to folder application/controllers then in api.php, on line 58 change the upload max file size.

Bye Rubens
